version: '2'
services:
  rails:
    build:
      context: .
      args:
        app_user: $USER
    image: svametcalf/docker-rails-demo
    volumes:
      - ".:/usr/src/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: docker:startup



  db:
    #build: db/build
    #image: svametcalf/docker-compose db
    image: postgres:9.5
    ports:
      - 5434:5432
